#the basics####
#use R studio
#load the package tidyverse
#arrows are used to assign objects (data aka a "dataframe" or "df" for short)
#control enter runs that line of code


#loading libraries
#you'll need to install these first by using the point and click menu
#tools > intall packages... then type these names exactly (R cares about upper/lower case)
library(dplyr)
library(tidyverse)
library(plyr)
library(psych)
library(knitr)
library(tidytext)
library(psych)

###### Resources ####
# -- How to downlaod etc R Studio https://www.rstudio.com/resources/webinars/rstudio-essentials-webinar-series-part-1/
# -- R studio cheat sheet https://www.rstudio.com/wp-content/uploads/2016/01/rstudio-IDE-cheatsheet.pdf
# -- so many more tutorials online for free including this amazing book https://r4ds.had.co.nz/
# -- Data Wrangling cheat sheet https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf
# -- A simple how to for importing Qualtrics data http://adrianbruegger.com/import-qualtrics-csv-files/
# -- Basic R studio tutorial http://web.cs.ucla.edu/~gulzar/rstudio/basic-tutorial.html


###### Importing data ####
##Option 1 = point and click in R studio
#file > import dataset
#will take SPSS files and excel and csv
#if importing an excel or non csv or text file, you can see the code preview in the bottom right
#you can just copy and paste that here if you want to save the code that was generated by options you selected

##Option 2 = use code
#import using a command
Part1 <- read.csv("2018Part1_raw.csv", stringsAsFactors = FALSE)
#you can click on the name "Part 1" in the "global environment" in the top R ->
#you'll see the data!


###### Renaming a few variables ####

#replace
transmute(Part1, newvariable = oldvariable)

#create a copy w a new name
mutate(Part1, newvariable = oldvariable)

#create a new variable
mutate(Part1, newvariable = oldvariable1 + oldvariable2)


###### Renaming a lot or most variables ####

#I often don't name the variables perfectly in Qualtrics and I want to rename them
#the way I like to do this for big datasets or multi-part datasets where I have T1, T2, etc. is
#to upload a file with all my names and then assign those names as names

#it's possible to change variable names lots of other ways 
#(you can create a new variable that is a copy but w a new name! you can use the mutate function in dplyr!)
#(you can also rename in Qualtrics and then download the csv again)
#I like this method because Qualtrics makes you change variable names by hand 
# I also like this method because slight discrepancies in caps and spacing matter in R and are super annoying
#so what I do is created an excel file that I saved as a CSV with the variable names that I want
#the variable names are arranged in the very first column
#even more specifically, I take the raw Qualtrics file and I copy the first row and then paste it as a column
#and then I just type over the old name, which helps me not make errors!

#once I have the list, I importing that file and save as a list called Part1_varnames
Part1_varnames <- read.csv("2018Part1_variablenames.csv", stringsAsFactors = FALSE, header = FALSE) %>% as.list() 
#then assign those names to Part1
names(Part1) <- Part1_varnames$V1 

###### Cleaning ####

Part1 <- Part1 %>% filter(grepl("^A", workerId)) %>% #Removing ugly rows and test responses (all mturk Ids start w A)
  select(-StartDate_T1, -Status_T1, -IPAddress_T1, -RecordedDate_T1, -ResponseId_T1,-RecipientLastName, -RecipientEmail, -RecipientFirstName, -ExternalReference, -LocationLatitude, -LocationLongitude, -DistributionChannel, -UserLanguage, -assignmentId, -hitId, -SC1, -`Errors - Topics`, -`Q319 - Topics`) %>% #removing columns we don't care about 
  filter(Screener != 7) %>% #selecting people who didn't fail the screener
  filter(Finished_T1 == 1) %>%  #selecting people who finished
  filter(Validity_random_T1 != 1) #selecting people who didn't say they answered Qs randomly

###### Merging datasets####
Parts1and2 <- left_join(Part1, Part2, by = "workerId") 


###### Recoding variables ####

#assigning new numeric values
#In this case we are recoding var1 to have levels 0 and 1 rather than 1 and 2
df$newvar1[df$oldvar1 == 2] <- 0 #for all values of oldvar1 equal to 2, assign the value of 0


#assigning text values to numeric variables
df$textvar1 <- factor(df$var1, levels = c(1,0), labels = c("Label for 1", "Label for 0"))

#######Calculating new variables from data across multiple rows

#row simple means, option 1
df$meanx <- (df$x1 + df$x2 + df$x3)/3

#row simple means, option 2
df <-  df %>% mutate(meanx = (x1+x2+x3)/3)

#row means where different obs have different numbers of contributing values, and you are matching a string
df <- df %>% mutate(
  meanx = rowMeans(.[grep("x[1-3]", names(.))], na.rm = TRUE)
)


###### Things that are useful for scales ####

#make sure you run the line of code above that says library(psych)

#reverse scoring for a 5 point scale
#someone who answered 5 will have a 1, someone who answered 1 will have a 5
df$Construct2R <- (6 - df$Construct2)
df$Construct4R <- (6 - df$Construct4)
df$Construct5R <- (6 - df$Construct5)
df$Construct9R <- (6 - df$Construct9)

#looking at correlations and calculating reliability
#I'm using a regular expression to grab all variables that begin with a string
#can also do specific strings like "^NameofConstruct[1-10]"
#adding a $ at the end means that's the end of the string to be matched "^NameofConstruct[1-10]$"
#you can also just type all the names of the variables, which I show below

#Step 1: create a new tiny dataset
#here, I grab all variables that start w the scale name
#then I remove any that were reverse scored and renamed with an R tag
scaledf <- df %>% select(matches("^NameofConstruct")) %>% 
  select(-NameofConstruct1, -NameofConstruct5)

#if I wanted to just type the names of my vars I'd do this
scaledf <- df %>% select(Construct1, Construct2R, Construct3, Construct4R, Construct5R, Construct6, Construct7, Construct8, Construct9R)

#Step 2: make and save a correlation matrix called scale.cor
scale.cor <- cor(scaledf, use = "pairwise.complete.obs")

#Step 3: sometimes it's nice to plot the correlations
cor.plot(scale.cor, numbers = TRUE, main = "Correlation of Scale Items")

#Step 4: calculate reliability
#to calculate and save alpha (package is psych)
scale_alpha <- alpha(scaledf)
scale_alpha #shows the results

#to calculate and save omega (package is psych)
scale_omega <- omega(scaledf)
scale_omega #shows the results

#Step 5: create a composite score
#note that some of these are reverse scored!
df$Construct <- (df$Construct1 + df$Construct2R + df$Construct3 + df$Construct4R + df$Construct5R + df$Construct6 + df$Construct7 + df$Construct8 + df$Construct9R)/9

#Step 6: look at descriptives
#describe is in the package psych
ConstructDescriptives <- describe(scale)
ConstructDescriptives #shows descriptives

